// Enums matching Prisma schema

export enum ContactStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PROSPECT = 'PROSPECT',
  CUSTOMER = 'CUSTOMER',
  FORMER_CUSTOMER = 'FORMER_CUSTOMER',
}

export enum AccountType {
  PROSPECT = 'PROSPECT',
  CUSTOMER = 'CUSTOMER',
  PARTNER = 'PARTNER',
  VENDOR = 'VENDOR',
  COMPETITOR = 'COMPETITOR',
}

export enum OpportunityStatus {
  OPEN = 'OPEN',
  WON = 'WON',
  LOST = 'LOST',
}

export enum ActivityStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PipelineType {
  SALES = 'SALES',
  SERVICE = 'SERVICE',
  PROJECT = 'PROJECT',
  SUPPORT = 'SUPPORT',
  ONBOARDING = 'ONBOARDING',
  RENEWAL = 'RENEWAL',
  CUSTOM = 'CUSTOM',
}

export enum ActivityCategory {
  CALL = 'CALL',
  EMAIL = 'EMAIL',
  MEETING = 'MEETING',
  SITE_VISIT = 'SITE_VISIT',
  INSPECTION = 'INSPECTION',
  ESTIMATE = 'ESTIMATE',
  PRESENTATION = 'PRESENTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  TASK = 'TASK',
  NOTE = 'NOTE',
  DOCUMENT = 'DOCUMENT',
  CUSTOM = 'CUSTOM',
}

export enum CustomFieldType {
  TEXT = 'TEXT',
  TEXTAREA = 'TEXTAREA',
  NUMBER = 'NUMBER',
  DECIMAL = 'DECIMAL',
  CURRENCY = 'CURRENCY',
  DATE = 'DATE',
  DATETIME = 'DATETIME',
  BOOLEAN = 'BOOLEAN',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  URL = 'URL',
  ADDRESS = 'ADDRESS',
  FILE = 'FILE',
  IMAGE = 'IMAGE',
  USER_REFERENCE = 'USER_REFERENCE',
  ENTITY_REFERENCE = 'ENTITY_REFERENCE',
  FORMULA = 'FORMULA',
  ROLLUP = 'ROLLUP',
}

export enum CRMEntityType {
  CONTACT = 'CONTACT',
  ACCOUNT = 'ACCOUNT',
  OPPORTUNITY = 'OPPORTUNITY',
  ACTIVITY = 'ACTIVITY',
  PROJECT = 'PROJECT',
  INVOICE = 'INVOICE',
  PRODUCT = 'PRODUCT',
  SERVICE = 'SERVICE',
}

export enum DocumentTemplateType {
  PROPOSAL = 'PROPOSAL',
  CONTRACT = 'CONTRACT',
  ESTIMATE = 'ESTIMATE',
  INVOICE = 'INVOICE',
  QUOTE = 'QUOTE',
  WORK_ORDER = 'WORK_ORDER',
  WARRANTY = 'WARRANTY',
  CERTIFICATE = 'CERTIFICATE',
  CHECKLIST = 'CHECKLIST',
  REPORT = 'REPORT',
  LETTER = 'LETTER',
  AGREEMENT = 'AGREEMENT',
}

export enum IntegrationType {
  WEATHER = 'WEATHER',
  AERIAL_IMAGERY = 'AERIAL_IMAGERY',
  MATERIAL_SUPPLIER = 'MATERIAL_SUPPLIER',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  ACCOUNTING = 'ACCOUNTING',
  EMAIL_MARKETING = 'EMAIL_MARKETING',
  SMS_MESSAGING = 'SMS_MESSAGING',
  CALENDAR = 'CALENDAR',
  MAP_LOCATION = 'MAP_LOCATION',
  CREDIT_CHECK = 'CREDIT_CHECK',
  LICENSING = 'LICENSING',
  INDUSTRY_DATA = 'INDUSTRY_DATA',
  CUSTOM = 'CUSTOM',
}

export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  MEMBER = 'MEMBER',
  VIEWER = 'VIEWER',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  PAUSED = 'PAUSED',
}

export enum IndustryTemplate {
  PROJECT_BASED = 'PROJECT_BASED',
  SALES_FOCUSED = 'SALES_FOCUSED',
  SERVICE_BASED = 'SERVICE_BASED',
  INVENTORY_BASED = 'INVENTORY_BASED',
  ASSET_BASED = 'ASSET_BASED',
  MEMBERSHIP_BASED = 'MEMBERSHIP_BASED',
  HOSPITALITY_BASED = 'HOSPITALITY_BASED',
  CASE_BASED = 'CASE_BASED',
}
